### ISSUE TITLE
Homey 2.0

### ISSUE THREAD

**Issue by johnniemalm** [sprut666666/com.sprut.homekit#36]
The app does not start in Homey V 2

**Comment by johnniemalm** [comment]
Sorry it does start, but units is not connected on home

**Comment by mhoogenbosch** [comment]
The last active change was about 9 months ago. I think this project is abandoned. Despite the 2.0.0RC experimental integration with HomeKit isn't working flawlessly, it does work. So my guess is to put your bets on that one.

**Comment by johnniemalm** [comment]
Done that, but not happy with it, this is much better

**Comment by Sannieslief** [comment]
Is there an update on this issue? 
Still unable to add homekit devices. 
Would be very nice of this would be fixed. :-)

**Comment by johnniemalm** [comment]
Ad Homeykit instead, works perfect

**Comment by Sannieslief** [comment]
Thanks for the quick reply! That indeed works perfect!
